# Generated by Django 3.2.3 on 2021-05-28 21:38

from django.db import migrations, models

import authentification.models


class Migration(migrations.Migration):
    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adress',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='', upload_to=authentification.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postalcode',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
